[server]
port = 5556

[node]
detect-drivers = false

[relay]
# Default Appium server endpoint
url = "http://127.0.0.1:4725"
status-endpoint = "/status"
protocol-version = "HTTP/1.1"
configs = [
    #    "1", "{\"appium:deviceName\": \"emulator-5554\", \"platformName\": \"ANDROID\", \"appium:platformVersion\": \"12\", \"appium:automationName\": \"UiAutomator2\",\"proxy\":{\"proxyType\":\"direct\",\"appium:chromeOptions\":{\"w3c\":false}}}"
    "1", "{\"browserName\": \"chrome\",\"appium:deviceName\": \"emulator-5554\", \"platformName\": \"android\", \"appium:platformVersion\": \"15\", \"appium:automationName\": \"UiAutomator2\"}"
    #    '1', '{"browserName": "chrome","appium:deviceName": "emulator-5554", "platformName": "android", "appium:platformVersion": "12", "appium:automationName": "UiAutomator2"}'
    #    '1', '{"platformName": "android", "appium:platformVersion": "14", "appium:deviceName": "emulator-5554", "appium:automationName": "uiautomator2", "appium:browserName": "chrome", "browserName": "chrome"}'
]