# node2.toml
[server]
port = 5565

[node]
detect-drivers = true

[relay]
url = "http://localhost:4727"
status-endpoint = "/status"
configs = [
    "1", "{\"platformName\": \"iOS\", \"appium:platformVersion\": \"15.0\", \"appium:deviceName\": \"iPhone 13\", \"appium:automationName\": \"XCUITest\"}"
]