[server]
port = 5556

[node]
detect-drivers = false

[relay]
# Default Appium server endpoint
url = "http://127.0.0.1:4723"
status-endpoint = "/status"
protocol-version = "HTTP/1.1"
configs = [
    "1", "{\"appium:deviceName\": \"emulator-5554\", \"platformName\": \"android\", \"appium:platformVersion\": \"15\", \"appium:automationName\": \"UiAutomator2\"}"
   ]